list            : $/martin/quotes/models/item/columns.yaml
modelClass      : Martin\Quotes\Models\Item
title           : martin.quotes::lang.controller.list.items
recordUrl       : martin/quotes/items/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage  : 20
showSetup       : true
showSorting     : true
defaultSort     :
    column   : id
    direction: asc
showCheckboxes  : true
toolbar         :
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt